package model;
// Generated 3.12.2013 12:14:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int customer_ID;
     private String name;
     @NotEmpty
     private String login;
     @NotEmpty
     private String password;
     private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

       
     
    public Customer() {
    }

	
    public Customer(int customer_ID, String name, String login, String password) {
        this.customer_ID = customer_ID;
        this.name = name;
        this.login = login;
        this.password = password;
    }
    public Customer(int customer_ID, String name, String login, String password, Set<UserRoles> userRoleses) {
       this.customer_ID = customer_ID;
       this.name = name;
       this.login = login;
       this.password = password;
       this.userRoleses = userRoleses;
    }
   
    public int getCustomer_ID() {
        return customer_ID;
    }

    public void setCustomer_ID(int customer_ID) {
        this.customer_ID = customer_ID;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }
    
    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }




}


