package model;
// Generated 16.4.2014 18:21:36 by Hibernate Tools 3.6.0



/**
 * EmployeeRole generated by hbm2java
 */
public class EmployeeRole  implements java.io.Serializable {


     private Integer roleId;
     private String role;

    public EmployeeRole() {
    }

    public EmployeeRole(String role) {
       this.role = role;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


