package model;
// Generated 3.12.2013 12:14:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int employeeId;
     private String name;
     private String login;
     private String password;
     private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

    public Employee() {
    }

	
    public Employee(int employeeId, String name, String login, String password) {
        this.employeeId = employeeId;
        this.name = name;
        this.login = login;
        this.password = password;
    }
    public Employee(int employeeId, String name, String login, String password, Set<UserRoles> userRoleses) {
       this.employeeId = employeeId;
       this.name = name;
       this.login = login;
       this.password = password;
       this.userRoleses = userRoleses;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }
    
    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }




}


