package model;

// Generated Apr 16, 2014 2:54:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer orderId;
	private User user;
	private String cityFrom;
	private String cityTo;
	private String streetFrom;
	private String streetTo;
	private Integer countOfKm;
	private Date date;

	public Order() {
	}

	public Order(User user, String cityFrom, String cityTo, String streetFrom, String streetTo, Date date) {
		this.user = user;
		this.cityFrom = cityFrom;
		this.cityTo = cityTo;
		this.streetFrom = streetFrom;
		this.streetTo = streetTo;
		this.date = date;
	}

	public Order(User user, String cityFrom, String cityTo, String streetFrom, String streetTo, Integer countOfKm, Date date) {
		this.user = user;
		this.cityFrom = cityFrom;
		this.cityTo = cityTo;
		this.streetFrom = streetFrom;
		this.streetTo = streetTo;
		this.countOfKm = countOfKm;
		this.date = date;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCityFrom() {
		return this.cityFrom;
	}

	public void setCityFrom(String cityFrom) {
		this.cityFrom = cityFrom;
	}

	public String getCityTo() {
		return this.cityTo;
	}

	public void setCityTo(String cityTo) {
		this.cityTo = cityTo;
	}

	public String getStreetFrom() {
		return this.streetFrom;
	}

	public void setStreetFrom(String streetFrom) {
		this.streetFrom = streetFrom;
	}

	public String getStreetTo() {
		return this.streetTo;
	}

	public void setStreetTo(String streetTo) {
		this.streetTo = streetTo;
	}

	public Integer getCountOfKm() {
		return this.countOfKm;
	}

	public void setCountOfKm(Integer countOfKm) {
		this.countOfKm = countOfKm;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
