package model;
// default package
// Generated Mar 19, 2014 11:06:25 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private Integer id;
	private String role;
	private Set users = new HashSet(0);

	public UserRole() {
	}

	public UserRole(String role) {
		this.role = role;
	}

	public UserRole(String role, Set users) {
		this.role = role;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer userRoleId) {
		this.id = userRoleId;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
