package model;

// Generated Apr 24, 2014 12:42:14 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer idUser;
	@NotEmpty
	private String username;
	@NotEmpty
	private String password;
	@NotEmpty
	private String name;
	@NotEmpty
	private String surname;
	@Email
	private String email;
	@NotEmpty
	private String phone;
	private String city;
	private String street;
	private String zip;
	private String hint;
	private String passphrase;
	private Set ordersForUserId = new HashSet(0);
	private Set<UserRole> userRoles = new HashSet(0);
	private Set ordersForIdUserDriver = new HashSet(0);

	public User() {
	}

	public User(String username, String password, String name, String surname, String email, String city, String street, String zip, String hint,
			String passphrase) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.city = city;
		this.street = street;
		this.zip = zip;
		this.hint = hint;
		this.passphrase = passphrase;
	}

	public User(String username, String password, String name, String surname, String email, String phone, String city, String street, String zip, String hint,
			String passphrase, Set ordersForUserId, Set userRoles, Set ordersForIdUserDriver) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.phone = phone;
		this.city = city;
		this.street = street;
		this.zip = zip;
		this.hint = hint;
		this.passphrase = passphrase;
		this.ordersForUserId = ordersForUserId;
		this.userRoles = userRoles;
		this.ordersForIdUserDriver = ordersForIdUserDriver;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getHint() {
		return this.hint;
	}

	public void setHint(String hint) {
		this.hint = hint;
	}

	public String getPassphrase() {
		return this.passphrase;
	}

	public void setPassphrase(String passphrase) {
		this.passphrase = passphrase;
	}

	public Set getOrdersForUserId() {
		return this.ordersForUserId;
	}

	public void setOrdersForUserId(Set ordersForUserId) {
		this.ordersForUserId = ordersForUserId;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

	public Set getOrdersForIdUserDriver() {
		return this.ordersForIdUserDriver;
	}

	public void setOrdersForIdUserDriver(Set ordersForIdUserDriver) {
		this.ordersForIdUserDriver = ordersForIdUserDriver;
	}

}
