package model;
// Generated 3.12.2013 12:14:03 by Hibernate Tools 3.6.0



/**
 * UserRoles generated by hbm2java
 */
public class UserRoles  implements java.io.Serializable {


     private UserRolesId id;
     private Customer customer;
     private Employee employee;
     private String authority;

    public UserRoles() {
    }

    public UserRoles(UserRolesId id, Customer customer, Employee employee, String authority) {
       this.id = id;
       this.customer = customer;
       this.employee = employee;
       this.authority = authority;
    }
   
    public UserRolesId getId() {
        return this.id;
    }
    
    public void setId(UserRolesId id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


