package model;
// default package
// Generated Mar 19, 2014 11:06:25 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String idUser;
	@NotEmpty
	private String username;
	@NotEmpty
	private String password;
	@NotEmpty
	private String name;
	@NotEmpty
	private String surname;
	@NotEmpty @Email
	private String email;
	@NotEmpty
	private String phone;
	@NotEmpty
	private String city;
	@NotEmpty
	private String street;
	@NotEmpty
	private String zip;
	private Set userRoles = new HashSet();
	
	private String hint;
	private String passphrase;

	public User() {
	}

	public User(String username, String password, String name, String surname,
			String EMail, String city, String street, String zip) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = EMail;
		this.city = city;
		this.street = street;
		this.zip = zip;
	}

	public User(String username, String password, String name, String surname,
			String EMail, String phone, String city, String street, String zip,
			Set userRoles) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = EMail;
		this.phone = phone;
		this.city = city;
		this.street = street;
		this.zip = zip;
		this.userRoles = userRoles;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public String getHint() {
		return hint;
	}

	public void setHint(String hint) {
		this.hint = hint;
	}

	public String getPassphrase() {
		return passphrase;
	}

	public void setPassphrase(String passphrase) {
		this.passphrase = passphrase;
	}
	
	

}
